config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts do
    resources :likes
    resources :comments
  end

  get "posts/filter/:filter" => "posts#index", as: "filtered_posts"

  resources :users

  get "users/:id/filter/:filter" => "users#show", as: "filtered_user_posts"

  resource :session, only: [:new, :create, :destroy]

  get "signup" => "users#new"
  get "signin" => "sessions#new"

end

app/models/user.rb
class User < ApplicationRecord
  before_save :set_slug

  has_secure_password

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy

  validates :email, email: true, presence: true,
            uniqueness: {case_sensitive: false}
  validates :username, presence: true,
            uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: 10, allow_blank: true}
  validate :acceptable_image

  def to_param
    slug
  end

  private

  def acceptable_image
    return unless profile_image.attached?

    unless profile_image.blob.byte_size <= 1.megabyte
      errors.add(:profile_image, "is too big")
    end

    acceptable_types = ["image/jpeg", "image/png"]

    unless acceptable_types.include?(profile_image.content_type)
      errors.add(:profile_image, "must be a JPEG or PNG")
    end
  end

  def set_slug
    self.slug = username.parameterize
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create, :show]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find_by!(slug: params[:id])

    case params[:filter]
    when "likes"
      @posts = @user.liked_posts.paginate(page: params[:page]).order('created_at DESC')
    else
      @posts = Post.where(:user_id => @user.id).paginate(page: params[:page]).order('created_at DESC')
    end

  end

  def new
    if current_user
      redirect_to root_path
    end

    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, success: "Thanks for signing up!"
    else
      render :new
    end

  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path,
                success: "Your account is successfully deleted!"
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user,
                  success: "Your account has updated successfully!"
    else
      render :edit
    end
  end

  private

  def require_correct_user
    @user = User.find_by!(slug: params[:id])
    redirect_to root_url unless current_user?(@user)
  end

  def user_params
    params.require(:user)
        .permit(:email, :username, :password, :password_confirmation, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <%= form_with(model: @user, local: true, class: 'mt-5') do |f| %>

    <%= render "shared/errors", object: @user %>

    <div class="d-flex justify-content-center my-5">
      <%= profile_image(@user, 200, 200) %>
    </div>

    <div class="form-group mb-3 d-flex justify-content-center">
      <%= f.file_field :profile_image, accept: "image/x-png,image/gif,image/jpeg" %>
    </div>

    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <div class="d-flex justify-content-center">
      <%= f.submit "Save Change", class: "btn btn-success" %>
    </div>

  <% end %>

  <div class="d-flex justify-content-center mt-3">
    <%= button_to "Delete Account", user_path(@user), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
  </div>
</div>

app/views/users/index.html.erb
<h1 class="text-center"><%= pluralize(@users.size, "User") %></h1>
<ul class="list-group">
  <% @users.each do |user| %>
    <li class="list-group-item">
      <div class="d-flex w-100 justify-content-between">
        <%= link_to user.username, user, class: "h5 font-weight-bold" %>
        <small><%= time_ago_in_words(user.created_at) %></small>
      </div>
      <p class="mb-1"><%= user.email %></p>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="container">
  <h1 class="text-center">Sign Up</h1>

  <%= form_with(model: @user, local: true) do |f| %>

    <%= render "shared/errors", object: @user %>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", required: true %>
      <small class="text-black-50">* Minimum 10 characters or numbers</small>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control", required: true %>
    </div>

    <p class="text-center">
      Do you have an account? <%= link_to "Sign In", signin_path, class: "text-success" %>
    </p>

    <div class="d-flex justify-content-center">
      <%= f.submit "Sign Up", class: "btn btn-success" %>
    </div>

  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="d-flex justify-content-center my-5">
    <%= profile_image(@user, 200, 200) %>
  </div>
  <ul class="list-group">
    <li class="list-group-item font-weight-bold text-center" style="background-color: #ebebec">
      <%= @user.username %>
    </li>

    <li class="list-group-item text-center" style="background-color: #ebebec">
      <%= @user.email %>
    </li>
  </ul>

  <div class="d-flex justify-content-center mt-5 font-weight-bold" style="font-size: 2rem">
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Filters
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= link_to "Mine", user_path(@user), class: "dropdown-item" %>
        <%= link_to "Likes", filtered_user_posts_path(@user, "likes"), class: "dropdown-item" %>
      </div>
    </div>
  </div>

  <%= render "shared/posts", posts: @posts %>
</div>