config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts do
    resources :likes
    resources :comments
  end

  get "posts/filter/:filter" => "posts#index", as: "filtered_posts"

  resources :users

  get "users/:id/filter/:filter" => "users#show", as: "filtered_user_posts"

  resource :session, only: [:new, :create, :destroy]

  get "signup" => "users#new"
  get "signin" => "sessions#new"

end

app/models/post.rb
class Post < ApplicationRecord
  before_save :set_slug

  has_one_attached :thumbnail_image
  has_rich_text :body
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validate :acceptable_image
  validates :title, presence: true, uniqueness: { case_sensitive: false }

  self.per_page = 3

  def to_param
    slug
  end

  private

  def acceptable_image
    return unless thumbnail_image.attached?

    unless thumbnail_image.blob.byte_size <= 1.megabyte
      errors.add(:thumbnail_image, "is too big")
    end

    acceptable_types = ["image/jpeg", "image/png"]

    unless acceptable_types.include?(thumbnail_image.content_type)
      errors.add(:thumbnail_image, "must be a JPEG or PNG")
    end
  end

  def set_slug
    self.slug = title.parameterize
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page]).order('created_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @user = @post.user
    @comments = @post.comments
    @comment = Comment.new

    @post.update!(views: @post.views + 1)

    if current_user
      @like = current_user.likes.find_by(post_id: @post.id)
    end

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    unless current_user?(@post.user)
      redirect_to root_path, danger: "You aren't authorized!"
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post, success: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.update(post_params)
      redirect_to @post, success: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    unless current_user?(@post.user)
      redirect_to root_path, danger: "You aren't authorized!"
    end

    @post.destroy
    redirect_to posts_url, success: 'Post was successfully deleted.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find_by!(slug: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :views, :body, :thumbnail_image)
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def thumbnail_image(post)
    if post.thumbnail_image.attached?
      image_tag post.thumbnail_image.variant(resize_to_limit: [300, 300]), class: "card-img-top", style: "max-height: 300px;"
    else
      image_tag "https://via.placeholder.com/300x300/20c997/FFFFFF?text=#{post.title}", class: 'card-img-top', style: "max-height: 300px"
    end
  end

end

app/views/posts/_commentForm.html.erb
<% uuid = SecureRandom.uuid %>

<div id="accordion-<%= uuid %>">
  <div class="card mt-3" style="background-color: #ebebec">
    <div id="heading-<%= uuid %>" class="mb-3">
      <div data-toggle="collapse" data-target="#collapse-<%= uuid %>" aria-expanded="true" aria-controls="collapse-<%= uuid %>">
        <small style="cursor:pointer"><%= fa_icon "plus-circle", class: "mr-1" %> Add Comment</small>
      </div>
    </div>

    <div id="collapse-<%= uuid %>" class="collapse" aria-labelledby="heading-<%= uuid %>" data-parent="#accordion-<%= uuid %>">
      <div class="card-body">
        <%= form_with(url: "/posts/#{@post.slug}/comments?parent_id=#{parent_id}", local: true) do |f| %>

          <div class="form-group">

            <%= f.text_field :content, required: true, class: "form-control" %>

          </div>

          <%= f.submit class: "btn btn-dark" %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_comments.html.erb
<% comments.each do |comment| %>
  <% user = comment.user %>
  <% subcomments = comment.subcomments %>

  <div class="container">
    <div class="media d-flex flex-column">
      <%= link_to user do %>
        <div class="d-flex">
          <%= profile_image(user, 50, 50) %>
          <div class="container">
            <div class="font-weight-bold"><small><%= user.username %></small></div>
            <div class="text-black-50"><small><%= comment.created_at.strftime("%F") %></small></div>
          </div>
        </div>
      <% end %>
      <div class="media-body mt-3">
        <div class="container d-flex flex-row align-items-center">
          <div class="mr-5"><%= comment.content %></div>
          <% if current_user?(user) %>
            <div><%= button_to "Delete", post_comment_path(@post, comment), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger" %></div>
          <% end %>
        </div>

        <% if subcomments.any? %>
          <div id="accordion-<%= comment.id %>">
            <div class="card mt-3" style="background-color: #ebebec">
              <div id="heading-<%= comment.id %>" class="mb-3 text-success" style="cursor: pointer">
                <div data-toggle="collapse" data-target="#collapse-<%= comment.id %>" aria-expanded="true" aria-controls="collapse-<%= comment.id %>">
                  <%= fa_icon "bars", class: "mr-1" %> <%= pluralize(subcomments.count, "Comment") %>
                </div>
              </div>

              <div id="collapse-<%= comment.id %>" class="collapse border-left border-success" aria-labelledby="heading-<%= comment.id %>" data-parent="#accordion-<%= comment.id %>">
                <div class="card-body">
                  <%= render "posts/comments", comments: subcomments %>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <%= render "posts/commentForm", parent_id: comment.id %>

      </div>
    </div>
  </div>
  <hr/>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, class: "mt-5") do |form| %>

  <%= render 'shared/errors', object: post %>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <%= form.label :title, class: "input-group-text" %>
    </div>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="input-group mb-3">
    <%= form.file_field :thumbnail_image, accept: "image/x-png,image/gif,image/jpeg" %>
    <%= form.label :thumbnail_image, "Choose thumbnail image", class: "custom-file-label" %>
  </div>

  <div class="field">
    <%= form.rich_text_area :body, required: true, class: "bg-white customized-min-height" %>
  </div>

  <div class="actions d-flex justify-content-center">
    <%= form.submit class: "btn btn-success my-3" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to @post, class: "text-dark" do %>
  <%= fa_icon "arrow-left" %> Back
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <%= render "shared/posts", posts: @posts %>
</div>

app/views/posts/new.html.erb
<div class="container">

  <%= render 'form', post: @post %>

  <%= link_to posts_path, class: "text-dark", :action => "go" do %>
    <%= fa_icon "arrow-left" %> Back
  <% end %>
</div>

app/views/posts/show.html.erb
<link href="https://vjs.zencdn.net/7.8.4/video-js.css" rel="stylesheet"/>

<div class="container">
  <div class="font-weight-bold mt-5" style="font-size: 5rem; overflow-wrap: break-word">
    <%= @post.title %>
  </div>

  <div class="my-5 d-flex justify-content-between">
    <div class="d-flex align-items-center">
      <span class="mr-2"><%= link_to @user.username, user_path(@user), class: "font-weight-bold" %></span>
      •
      <span class="text-black-50 ml-2"><%= @post.created_at.strftime("%F") %></span>
    </div>
    <div>
      <%= like_or_unlike_button(@post, @like) %>
    </div>
  </div>

  <div class="my-5">
    <%= thumbnail_image(@post) %>
  </div>

  <div>
    <%= @post.body %>
  </div>
</div>

<% if current_user?(@user) %>
  <div class="d-flex justify-content-center my-5">
    <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning mr-3" %>
    <%= link_to 'Delete', post_path(@post), method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure?"} %>
  </div>
<% end %>

<hr/>

<div>
  <%= render "posts/commentForm", parent_id: '' %>
</div>

<hr/>

<%= render "posts/comments", comments: @comments.parents %>

<script src="https://vjs.zencdn.net/7.8.4/video.js"></script>