config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts do
    resources :likes
    resources :comments
  end

  get "posts/filter/:filter" => "posts#index", as: "filtered_posts"

  resources :users

  get "users/:id/filter/:filter" => "users#show", as: "filtered_user_posts"

  resource :session, only: [:new, :create, :destroy]

  get "signup" => "users#new"
  get "signin" => "sessions#new"

end

app/views/layouts/_flash.html.erb
<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>

<% if flash[:danger] %>
  <div class="alert alert-danger">
    <%= flash[:danger] %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light" style="z-index: 5">
  <%= link_to "BBS", root_path, class: "navbar-brand font-weight-bold", style: "font-size: 3rem" %>
  <div type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <% if current_user %>
      <%= profile_image(current_user, 40, 40) %> <%= fa_icon "angle-down" %>
    <% else %>
      <%= link_to "Sign In", signin_path, class: "btn btn-dark" %>
    <% end %>
  </div>
</nav>
<div class="d-flex justify-content-end">
  <ul class="list-group collapse position-absolute" style="z-index: 5" id="navbarNav">
    <li class="list-group-item">
      <div class="nav-item mb-3">
        <%= link_to "My Posts", current_user, class: "text-dark" %>
      </div>
      <div class="nav-item mb-3">
        <%= link_to "New Post", new_post_path, class: "text-dark" %>
      </div>
      <% if current_user %>
        <div class="nav-item mb-3">
          <%= link_to "Account Settings", edit_user_path(current_user), class: "text-dark" %>
        </div>
        <div class="nav-item mb-3">
          <%= link_to "Sign Out", session_path, method: :delete, class: "text-dark" %>
        </div>
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BBS</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag asset_path('favicon.ico') %>
</head>

<body>
<%= render "layouts/header" %>
<%= render "layouts/flash" %>
<%= yield %>
</body>
</html>